### ISSUE TITLE
Header/Nav Bar Style

### ISSUE THREAD

**Issue by jordanwillis** [smileww/prj-rev-bwfs-tea-cozy#2]
This is just a quick recommendation to add a solid black background to your header/nav bar.  The overall structure and style look great but I noticed that when I scrolled down in the page the header was transparent.

Adding a `background-color` to your `.header` selector should do the trick.

``` css
.header {
  display: flex;
  padding: 0px;
  height: 69px;
  position: fixed;
  border-bottom: 1px solid seashell;
  align-items: center;
  justify-content: space-between;
  width: 100%;
  z-index: 1;
  margin: 0;
  background-color: black;
}
```
